name: Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
    - name: Clean Build
      run: xcodebuild clean build -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CUIExpandableButton
          DESTINATION: platform=iOS Simulator,name=iPhone 13 Pro
          
  test:
    needs: build
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
    - name: Test
      run: xcodebuild test -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CUIExpandableButton
          DESTINATION: platform=iOS Simulator,name=iPhone 13 Pro
